FROM python:3.12-alpine AS builder

WORKDIR /app

COPY src/services/simulation_service/core/infrastructure/server/server_requirements.txt .
RUN pip install --no-cache-dir uv && \
    uv pip install --no-cache-dir -r server_requirements.txt --target /install

FROM python:3.12-alpine

WORKDIR /app


COPY --from=builder /install /usr/local/lib/python3.12/site-packages
COPY src/services/simulation_service/core/infrastructure/server/src/ /app/
COPY src/services/simulation_service/core/infrastructure/generated/ /app/generated/
COPY src/services/simulation_service/core/connectors/ /app/connectors/
COPY src/services/simulation_service/core/utils/ /app/utils/

COPY src/logger /app/logger

ENV PYTHONPATH=/app/generated
ENV URGENT_LOGGER_PROFILE=server

ARG _SERVER_PORT

ENV SERVER_PORT=${_SERVER_PORT}

CMD ["python", "-u", "_simulation_server_grpc.py"]
