FROM python:3.12-slim AS builder

WORKDIR /app

COPY src/services/simulation_service/core/infrastructure/worker/worker_requirements.txt .
RUN pip install --no-cache-dir -r worker_requirements.txt --target /install

FROM python:3.12-slim

WORKDIR /app

COPY src/services/simulation_service/core/infrastructure/worker/src/ /app/
COPY src/services/simulation_service/core/infrastructure/generated/ /app/generated/
COPY src/services/simulation_service/core/connectors/ /app/connectors/
COPY src/services/simulation_service/core/utils/ /app/utils/

COPY src/logger /app/logger

COPY --from=builder /install /usr/local/lib/python3.12/site-packages

ENV PYTHONPATH=/app:/app/generated
ENV URGENT_LOGGER_PROFILE=worker

ARG _SERVER_PORT
ARG _SERVER_HOST

ENV SERVER_PORT=${_SERVER_PORT}
ENV SERVER_HOST=${_SERVER_HOST}

CMD ["python", "-u", "_simulation_worker_grpc.py"]
