FROM python:3.12.12-slim AS builder

WORKDIR /app

COPY src/services/simulation_service/core/infrastructure/worker/open_darts_whl/ /app/open_darts_whl/
COPY src/services/simulation_service/core/infrastructure/worker/worker_requirements.txt .
RUN pip install --no-cache-dir uv && \
    uv pip install --no-cache-dir -r worker_requirements.txt --target /install

FROM python:3.12.12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /install /usr/local/lib/python3.12/site-packages
COPY pyproject.toml /app/pyproject.toml

# Copy only necessary source files to minimize python dependency mismatch
COPY src/logger/ /app/src/logger/

COPY src/common/__init__.py /app/src/common/__init__.py
COPY src/common/models/ /app/src/common/models/

COPY src/services/__init__.py /app/src/services/__init__.py
COPY src/services/simulation_service/__init__.py /app/src/services/simulation_service/__init__.py

COPY src/services/simulation_service/core/__init__.py /app/src/services/simulation_service/core/__init__.py
COPY src/services/simulation_service/core/config.py /app/src/services/simulation_service/core/config.py

COPY src/services/simulation_service/core/connectors/ /app/src/services/simulation_service/core/connectors/

COPY src/services/simulation_service/core/utils/__init__.py /app/src/services/simulation_service/core/utils/__init__.py
COPY src/services/simulation_service/core/utils/converters.py /app/src/services/simulation_service/core/utils/converters.py

COPY src/services/simulation_service/core/infrastructure/__init__.py /app/src/services/simulation_service/core/infrastructure/__init__.py
COPY src/services/simulation_service/core/infrastructure/generated/ /app/src/services/simulation_service/core/infrastructure/generated/

COPY src/services/simulation_service/core/infrastructure/worker/src/ /app/src/services/simulation_service/core/infrastructure/worker/src/

COPY src/urgent_plugins/ /app/src/urgent_plugins/
COPY src/utils.py /app/src/utils.py
COPY src/services/shared/ /app/src/services/shared/
COPY src/services/solution_updater_service/ /app/src/services/solution_updater_service/
COPY src/services/problem_dispatcher_service/ /app/src/services/problem_dispatcher_service/
COPY src/services/well_management_service/ /app/src/services/well_management_service/


COPY plugins/ /app/plugins/
ENV PYTHONPATH=/app/src:/app/plugins
ENV URGENT_LOGGER_PROFILE=worker

ARG _SERVER_PORT
ARG _SERVER_HOST

ENV SERVER_PORT=${_SERVER_PORT}
ENV SERVER_HOST=${_SERVER_HOST}

CMD ["python", "-u", "-m", "services.simulation_service.core.infrastructure.worker.src._simulation_worker_grpc"]
