name: simulation

services:
  server:
    image: simulation-server:latest
    build:
      context: ../../../../
      dockerfile: src/services/simulation_service/core/infrastructure/server/Dockerfile.server
      args:
        _SERVER_PORT: 50051
    container_name: simulation-server
    networks:
      - grpc-network
    ports:
      - "50051:50051"
    environment:
      - RUNNER_MODE=${RUNNER_MODE:-docker}
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import os, socket; socket.create_connection(('127.0.0.1', int(os.environ.get('SERVER_PORT', '50051'))), timeout=5).close()",
        ]
      interval: 10s
      timeout: 5s
      start_period: 0s
      start_interval: 0s
      retries: 3


  worker:
    image: simulation-worker:latest
    build:
      context: ../../../../
      dockerfile: src/services/simulation_service/core/infrastructure/worker/Dockerfile.worker
      args:
        _SERVER_PORT: 50051
        _SERVER_HOST: simulation-server
    depends_on:
      server:
        condition: service_healthy
    networks:
      - grpc-network
    environment:
      - RUNNER_MODE=${RUNNER_MODE:-docker}
    deploy:
      replicas: 1

networks:
  grpc-network:
    driver: bridge
