name: simulation

services:
  server:
    image: simulation-server:latest
    build:
      context: ../../../../
      dockerfile: src/services/simulation_service/core/infrastructure/server/Dockerfile.server
      args:
        _SERVER_PORT: 50051
    container_name: simulation-server
    networks:
      - grpc-network
    ports:
      - "50051:50051"
    environment:
      - OPEN_DARTS_RUNNER=${OPEN_DARTS_RUNNER:-docker}
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "50051" ]
      interval: 10s
      timeout: 5s
      start_period: 0s
      start_interval: 0s
      retries: 3


  worker:
    image: simulation-worker:latest
    build:
      context: ../../../../
      dockerfile: src/services/simulation_service/core/infrastructure/worker/Dockerfile.worker
      args:
        _SERVER_PORT: 50051
        _SERVER_HOST: simulation-server
    depends_on:
      server:
        condition: service_healthy
    networks:
      - grpc-network
    environment:
      - OPEN_DARTS_RUNNER=${OPEN_DARTS_RUNNER:-docker}
    deploy:
      replicas: 1

networks:
  grpc-network:
    driver: bridge
