services:
  server:
    image: simulation_server:latest
    build:
      context: .
      dockerfile: infrastructure/server/Dockerfile.server
      args:
        _SERVER_PORT: 50051
    container_name: simulation_server
    networks:
      - grpc-network
    ports:
      - "50051:50051"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "50051" ]
      interval: 10s
      timeout: 5s
      start_period: 0s
      start_interval: 0s
      retries: 3


  worker:
    image: simulation_worker:latest
    build:
      context: .
      dockerfile: infrastructure/worker/Dockerfile.worker
      args:
        _SERVER_PORT: 50051
        _SERVER_HOST: simulation_server
    depends_on:
      server:
        condition: service_healthy
    networks:
      - grpc-network
    deploy:
      replicas: 1

networks:
  grpc-network:
    driver: bridge
