name: Docker Build and Verify

on:
  push:
    branches:
      - main
      - docker-workflow
  pull_request:
    branches:
      - main

runs:
  using: 'docker'
  image: 'src/services/simulation_service/core/infrastructure/server/Dockerfile.server'
