name: Docker Build and Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Compose
        run: docker-compose -f src/services/simulation_service/core/docker-compose.yml build
